#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check ESLint Standards
npx --no-install commitlint --edit "$1" ||
(
  echo '👋 Hey yuo typed a wrong message! 👋 
    Commitlint ensures you keep best practices by enforcing you to follow them!'
  false; 
)

echo '🎉🎊🥳 Awesome, your commit rocks all over the place!'
